#!/usr/bin/env bash

UNIT_BASE="bmwi"

ARRAY_INTERFACES=(
can0
can1
ibus
kbus
lcd
)
# dbus

service_name() {
	echo "${UNIT_BASE}@${1}.service"
}

service_cmd() {
	local SERVICE_NAME

	for INTERFACE in "${ARRAY_INTERFACES[@]}"; do
		SERVICE_NAME="$(service_name "${INTERFACE}")"

		if [[ "${1}" == "start" || "${1}" == "restart" ]]; then
			if ! systemctl -q is-enabled "${SERVICE_NAME}" 2> /dev/null; then
				echo "Skipping disabled service '${SERVICE_NAME}'"
				continue
			fi
		fi

		[[ "${2}" != "-q" ]] && echo "Performing '${1}' '${SERVICE_NAME}'"

		sudo systemctl "${1}" "${SERVICE_NAME}"
		[[ "${1}" == "status" ]] && echo
	done
}


if [[ "${1}" ]]; then
	service_cmd "${1}"
	echo
else
	service_cmd status -q
fi
