#!/usr/bin/env bash

# Alternate directory for separate settings file
HOME="${HOME}/.toprc-service"
mkdir -p "${HOME}"

top -p "$(ps -e -o pid,cmd | awk '/[b]luealsa\ |[b]luealsa\-aplay/ {printf $1 ","}' | sed 's/,$//g')"
